# Configuration for Travis CI
language: java
matrix:
  include:
    - jdk: oraclejdk11
    - jdk: oraclejdk10
    - jdk: oraclejdk9
    - jdk: oraclejdk8
branches:
  only:
    - master
git:
  depth: 1000
# End .travis.yml
